/**
 * ==============================================================================
 * STEP 2 — Identity Verification (New Users Only)
 * ==============================================================================
 * Renders dynamically using the `ROLE_FIELDS_CONFIG` schema for the selected role.
 * Key Features:
 * 1. Config-driven dynamic field generation (no hardcoded six forms).
 * 2. Auto-fill from Step 1 (Mine Code / Assigned Mine Site).
 * 3. Simulated Statutory Verification badges (UAN/EPFO, DGMS, Executive Registry).
 * 4. Stores all values into `sessionContext.profile` and links identity anchor.
 * ==============================================================================
 */

import React, { useState, useEffect } from "react";
import { useSessionContext } from "../../context/SessionContext";
import { ROLES, ROLE_FIELDS_CONFIG } from "../../data/rolesConfig";
import {
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  FileCheck,
  Building,
  Upload,
  Info,
  CheckCircle,
  Sparkles,
} from "lucide-react";

export function Step2Identity() {
  const { state, updateProfile, goToStep } = useSessionContext();
  const currentRole = state.role || "Mine Official";
  const fieldsConfig = ROLE_FIELDS_CONFIG[currentRole] || [];
  const currentRoleDef = ROLES.find((r) => r.id === currentRole);

  const [formData, setFormData] = useState(() => {
    const initial = { ...state.profile };
    // Auto-fill values from Step 1 context
    fieldsConfig.forEach((f) => {
      if (f.autoFillFrom === "mineSiteCode") {
        initial[f.name] = state.mineSiteCode || state.mineSite || "ECL-SNB-01";
      } else if (f.autoFillFrom === "mineSiteName") {
        initial[f.name] = `${state.mineSite || "Assigned Mine"} (${state.mineSiteCode || state.subsidiary})`;
      } else if (f.autoGenerateDevice && !initial[f.name]) {
        initial[f.name] = `DEV-${Math.floor(100000 + Math.random() * 900000)}`;
      } else if (initial[f.name] === undefined && f.defaultValue !== undefined) {
        initial[f.name] = f.defaultValue;
      }
    });
    return initial;
  });

  // Keep synced if state profile changes (e.g., demo auto-fill)
  useEffect(() => {
    if (state.profile && Object.keys(state.profile).length > 0) {
      setFormData((prev) => ({
        ...prev,
        ...state.profile,
      }));
    }
  }, [state.profile]);

  const handleFieldChange = (name, value) => {
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleMultiselectToggle = (name, option) => {
    setFormData((prev) => {
      const currentList = Array.isArray(prev[name]) ? prev[name] : [];
      const updated = currentList.includes(option)
        ? currentList.filter((item) => item !== option)
        : [...currentList, option];
      return { ...prev, [name]: updated };
    });
  };

  const handleFileUpload = (name, e) => {
    const file = e.target.files?.[0];
    if (file) {
      setFormData((prev) => ({
        ...prev,
        [name]: file.name,
        [`${name}_size`]: `${(file.size / 1024).toFixed(1)} KB`,
      }));
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    updateProfile(formData);
    goToStep(3);
  };

  return (
    <div className="w-full max-w-2xl mx-auto">
      {/* Step Header */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-600 dark:text-amber-400 text-xs font-bold tracking-wider uppercase mb-3">
          <Sparkles className="w-3.5 h-3.5" />
          Step 2 of 4: Role-Specific Identity Verification
        </div>
        <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Verify {currentRole} Credentials
        </h2>
        <p className="text-sm text-slate-600 dark:text-slate-400 mt-2 max-w-lg mx-auto">
          Mapped for <span className="font-semibold text-amber-600 dark:text-amber-400">{state.mineSite || "Assigned Unit"}</span> (
          {state.subsidiary || "Coal Entity"}). Fields are dynamically configured for statutory governance.
        </p>
      </div>

      {/* Simulated Verification Master Badge */}
      {currentRoleDef?.verificationBadge && (
        <div className="mb-6 p-3.5 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-300 dark:border-emerald-700/60 flex items-center justify-between gap-3 text-xs text-emerald-800 dark:text-emerald-300 shadow-sm animate-fadeIn">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-emerald-600 dark:text-emerald-400 shrink-0" />
            <span className="font-semibold">{currentRoleDef.verificationBadge}</span>
          </div>
          <span className="px-2 py-0.5 rounded-full bg-emerald-600 text-white font-mono text-[10px] tracking-wider uppercase">
            Simulated Check
          </span>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
          {fieldsConfig.map((field) => {
            const isFullWidth = field.type === "radio" || field.type === "multiselect" || field.type === "daterange" || field.type === "file";

            return (
              <div key={field.name} className={`space-y-2 ${isFullWidth ? "sm:col-span-2" : ""}`}>
                <div className="flex items-center justify-between">
                  <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                    {field.label} {field.required && <span className="text-rose-500">*</span>}
                  </label>
                  {field.isAnchor && (
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-amber-100 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border border-amber-300/60 dark:border-amber-700/50">
                      Anchor ID
                    </span>
                  )}
                </div>

                {/* TEXT / NUMBER INPUT */}
                {(field.type === "text" || field.type === "number") && (
                  <input
                    type={field.type}
                    value={formData[field.name] || ""}
                    onChange={(e) => handleFieldChange(field.name, e.target.value)}
                    readOnly={field.readOnly}
                    required={field.required}
                    placeholder={field.placeholder}
                    className={`w-full h-11 px-3.5 rounded-xl border-2 text-sm font-medium focus:outline-none transition-all shadow-sm ${
                      field.readOnly
                        ? "bg-slate-100 dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-slate-500 dark:text-slate-400 cursor-not-allowed"
                        : "bg-slate-50 dark:bg-slate-900/90 border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 focus:border-amber-500"
                    }`}
                  />
                )}

                {/* SELECT DROPDOWN */}
                {field.type === "select" && (
                  <select
                    value={formData[field.name] || field.defaultValue || ""}
                    onChange={(e) => handleFieldChange(field.name, e.target.value)}
                    required={field.required}
                    className="w-full h-11 px-3.5 rounded-xl bg-slate-50 dark:bg-slate-900/90 border-2 border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 text-sm font-medium focus:border-amber-500 focus:outline-none transition-all shadow-sm"
                  >
                    {field.options?.map((opt) => (
                      <option key={opt} value={opt}>
                        {opt}
                      </option>
                    ))}
                  </select>
                )}

                {/* RADIO BUTTONS */}
                {field.type === "radio" && (
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    {field.options?.map((opt) => (
                      <label
                        key={opt}
                        className={`flex items-center gap-2.5 p-3 rounded-xl border-2 text-xs font-semibold cursor-pointer transition-all ${
                          formData[field.name] === opt
                            ? "bg-amber-500/10 border-amber-500 text-amber-700 dark:text-amber-300"
                            : "bg-slate-50 dark:bg-slate-900/80 border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 hover:border-slate-300"
                        }`}
                      >
                        <input
                          type="radio"
                          name={field.name}
                          value={opt}
                          checked={formData[field.name] === opt}
                          onChange={(e) => handleFieldChange(field.name, e.target.value)}
                          className="text-amber-500 focus:ring-amber-500"
                        />
                        <span>{opt}</span>
                      </label>
                    ))}
                  </div>
                )}

                {/* MULTI-SELECT CHIPS */}
                {field.type === "multiselect" && (
                  <div className="flex flex-wrap gap-2 pt-1">
                    {field.options?.map((opt) => {
                      const isSelected = Array.isArray(formData[field.name]) && formData[field.name].includes(opt);
                      return (
                        <button
                          key={opt}
                          type="button"
                          onClick={() => handleMultiselectToggle(field.name, opt)}
                          className={`px-3 py-1.5 rounded-lg border text-xs font-medium transition-all ${
                            isSelected
                              ? "bg-amber-500 text-navy-950 font-bold border-amber-500 shadow-sm"
                              : "bg-slate-100 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-200"
                          }`}
                        >
                          {isSelected ? "✓ " : "+ "}
                          {opt}
                        </button>
                      );
                    })}
                  </div>
                )}

                {/* DATE RANGE */}
                {field.type === "daterange" && (
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <span className="text-[11px] text-slate-500 dark:text-slate-400 mb-1 block">Start Date:</span>
                      <input
                        type="date"
                        value={formData[field.name]?.start || field.defaultStart || "2024-04-01"}
                        onChange={(e) =>
                          handleFieldChange(field.name, {
                            ...(formData[field.name] || {}),
                            start: e.target.value,
                          })
                        }
                        className="w-full h-11 px-3 rounded-xl bg-slate-50 dark:bg-slate-900 border-2 border-slate-200 dark:border-slate-800 text-sm font-medium"
                      />
                    </div>
                    <div>
                      <span className="text-[11px] text-slate-500 dark:text-slate-400 mb-1 block">End Date:</span>
                      <input
                        type="date"
                        value={formData[field.name]?.end || field.defaultEnd || "2027-03-31"}
                        onChange={(e) =>
                          handleFieldChange(field.name, {
                            ...(formData[field.name] || {}),
                            end: e.target.value,
                          })
                        }
                        className="w-full h-11 px-3 rounded-xl bg-slate-50 dark:bg-slate-900 border-2 border-slate-200 dark:border-slate-800 text-sm font-medium"
                      />
                    </div>
                  </div>
                )}

                {/* FILE UPLOAD (SIMULATED) */}
                {field.type === "file" && (
                  <div className="p-4 rounded-xl border-2 border-dashed border-slate-300 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-900/50 flex flex-col items-center justify-center text-center">
                    <Upload className="w-6 h-6 text-amber-500 mb-2" />
                    <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                      {formData[field.name] || "Click to upload statutory document (PDF / Image)"}
                    </p>
                    <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">
                      {formData[`${field.name}_size`] ? `Uploaded size: ${formData[`${field.name}_size`]}` : "Max size 10MB (Simulated OCR check)"}
                    </p>
                    <input
                      type="file"
                      accept={field.accept}
                      onChange={(e) => handleFileUpload(field.name, e)}
                      className="mt-2 text-xs text-slate-500 file:mr-2 file:py-1 file:px-3 file:rounded-md file:border-0 file:text-xs file:font-semibold file:bg-amber-500 file:text-navy-950 cursor-pointer"
                    />
                  </div>
                )}

                {/* TOGGLE */}
                {field.type === "toggle" && (
                  <label className="flex items-center justify-between p-3 rounded-xl bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 cursor-pointer">
                    <span className="text-xs text-slate-700 dark:text-slate-300 font-medium">
                      {field.hint || "Enable feature for this device"}
                    </span>
                    <input
                      type="checkbox"
                      checked={Boolean(formData[field.name] ?? field.defaultValue)}
                      onChange={(e) => handleFieldChange(field.name, e.target.checked)}
                      className="w-4 h-4 text-amber-500 rounded focus:ring-amber-500"
                    />
                  </label>
                )}

                {/* HINTS & COMPLIANCE NOTES */}
                {field.hint && field.type !== "toggle" && (
                  <p className="text-[11px] text-slate-500 dark:text-slate-400">{field.hint}</p>
                )}

                {field.complianceNote && (
                  <div className="p-2.5 rounded-lg bg-amber-500/10 border border-amber-500/30 text-[11px] text-amber-700 dark:text-amber-300 flex items-start gap-1.5">
                    <Info className="w-3.5 h-3.5 text-amber-600 shrink-0 mt-0.5" />
                    <span>{field.complianceNote}</span>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Buttons: Back + Continue */}
        <div className="pt-4 flex items-center gap-3">
          <button
            type="button"
            onClick={() => goToStep(1)}
            className="w-1/3 h-13 py-3 px-4 rounded-xl border-2 border-slate-300 dark:border-slate-700 font-bold text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back</span>
          </button>
          <button
            type="submit"
            className="w-2/3 h-13 py-3.5 px-6 rounded-xl font-bold text-base flex items-center justify-center gap-2 shadow-lg bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-navy-950 shadow-amber-500/20 active:scale-[0.99] cursor-pointer transition-all"
          >
            <span>Proceed to Step 3: Credentials</span>
            <ArrowRight className="w-5 h-5" />
          </button>
        </div>
      </form>
    </div>
  );
}
